export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SAVE_LOGGED_IN_USER_DATA = 'SAVE_LOGGED_IN_USER_DATA';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SAVE_REGISTERED_USER_DATA = 'SAVE_REGISTERED_USER_DATA';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';