//login-register types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SAVE_LOGGED_IN_USER_DATA = 'SAVE_LOGGED_IN_USER_DATA';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SAVE_REGISTERED_USER_DATA = 'SAVE_REGISTERED_USER_DATA';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const CLEAR_REGISTER_RELATED_ERROR = "CLEAR_REGISTER_RELATED_ERROR";
export const LOGOUT = "LOGOUT";
export const CLEAR_LOGIN_RELATED_ERROR = "CLEAR_LOGIN_RELATED_ERROR";
export const UPDATE_TEXT_PROFILE = "UPDATE_TEXT_PROFILE";


//practice question types
export const SELECT_SUBJECT = "SELECT_SUBJECT"
export const SELECT_YEAR = "SELECT_YEAR"
export const SAVE_PAST_QUESTION_TO_STATE = "SAVE_PAST_QUESTION_TO_STATE";
export const API_ERROR = "API_ERROR";
export const SELECT_PAST_QUESTION_PRACTICE_TYPE = "SELECT_PAST_QUESTION_PRACTICE_TYPE";
export const SELECT_ANSWER = "SELECT_ANSWER"
export const SUBMIT_USER_ANSWERS = "SUBMIT_USER_ANSWERS"
export const ON_SIDENAV_YEAR_CHANGE = "ON_SIDENAV_YEAR_CHANGE"
export const IS_VIEW_SOLUTION = "IS_VIEW_SOLUTION"
export const FILTER_SOLUTION = "FILTER_SOLUTION"
export const TEST_AGAIN = "TEST_AGAIN"
export const ANSWERED_QUESTION_FROM_STH = "ANSWERED_QUESTION_FROM_STH"
export const TIME_REMAINING = "TIME_REMAINING"
export const ANSWERED_SAME_PQ_BEFORE = "ANSWERED_SAME_PQ_BEFORE"
export const VIEW_SCORE_BY_PRACTICE_QUESTION_TYPE = "VIEW_SCORE_BY_PRACTICE_QUESTION_TYPE"
export const JUST_ANSWERED_QUESTION_ARRAY = "JUST_ANSWERED_QUESTION_ARRAY"


//PROFILE types
export const SAVE_PROFILE_DATA_TO_STATE = "SAVE_PROFILE_DATA_TO_STATE"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const POPULATE_PROFILE_DATA = "POPULATE_PROFILE_DATA"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const SAVE_UPDATED_PROFILE_DATA_TO_STATE = "SAVE_UPDATED_PROFILE_DATA_TO_STATE"