//login-register types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SAVE_LOGGED_IN_USER_DATA = 'SAVE_LOGGED_IN_USER_DATA';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SAVE_REGISTERED_USER_DATA = 'SAVE_REGISTERED_USER_DATA';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const CLEAR_REGISTER_RELATED_ERROR = "CLEAR_REGISTER_RELATED_ERROR";
export const LOGOUT = "LOGOUT";
export const CLEAR_LOGIN_RELATED_ERROR = "CLEAR_LOGIN_RELATED_ERROR";

//practice question types
export const SELECT_SUBJECT = "SELECT_SUBJECT"
export const SELECT_YEAR = "SELECT_YEAR"
export const SAVE_PAST_QUESTION_TO_STATE = "SAVE_PAST_QUESTION_TO_STATE";
export const API_ERROR = "API_ERROR";
export const SELECT_PAST_QUESTION_PRACTICE_TYPE = "SELECT_PAST_QUESTION_PRACTICE_TYPE";
export const SELECT_ANSWER = "SELECT_ANSWER"
export const SUBMIT_USER_ANSWERS =  "SUBMIT_USER_ANSWERS"
export const ON_SIDENAV_YEAR_CHANGE = "ON_SIDENAV_YEAR_CHANGE"