export const TutorialData = [
  {
    id: "1",
    courseName: "Introduction to Cells",
    viewsNumber: "2k",
    lectureNumber: 2,
    timeNumber: "1hr",
    tutorName: "Doris Peluola",
    ratingCount: 5,
    url: "RG9TMn1FJzc",
  },
  {
    id: "2",
    courseName: "Introduction to Living Things",
    viewsNumber: "1k",
    lectureNumber: 3,
    timeNumber: "2hr",
    tutorName: "Doris Peluola",
    ratingCount: 5,
    url: "E1KkQrFEl2I",
  },
  {
    id: "3",
    courseName: "Introduction to Organisms",
    viewsNumber: "2k",
    lectureNumber: 2,
    timeNumber: "1hr",
    tutorName: "Doris Peluola",
    ratingCount: 5,
    url: "cC9r0jHF-Fw",
  },
  {
    id: "4",
    courseName: "Introduction to Non-Living Things",
    viewsNumber: "2k",
    lectureNumber: 2,
    timeNumber: "1hr",
    tutorName: "Doris Peluola",
    ratingCount: 5,
    url: "E1KkQrFEl2I",
  },
  {
    id: "5",
    courseName: "Introduction to Cells",
    viewsNumber: "2k",
    lectureNumber: 2,
    timeNumber: "1hr",
    tutorName: "Doris Peluola",
    ratingCount: 5,
    url: "cC9r0jHF-Fw",
  },
  {
    id: "6",
    courseName: "Introduction to Cells",
    viewsNumber: "2k",
    lectureNumber: 2,
    timeNumber: "1hr",
    tutorName: "Doris Peluola",
    ratingCount: 5,
    url: "E1KkQrFEl2I",
  },
];
